name: Staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 9 * * *' # 09:30am See https://crontab.guru/#30_9_*_*_*

jobs:
  staging-example:

    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v2
    - name: Install amber
      run: |
        curl -L https://github.com/fpco/amber/releases/download/v0.1.1/amber-x86_64-unknown-linux-musl > amber
        chmod +x amber
    - name: Verify amber
      env:
        AMBER_SECRET: ${{ secrets.AMBER_SECRET }}
      run: |
        # Example printing secrets
        ./amber print --amber-yaml amber-staging.yaml
        # Example using secrets with automatic masking of secrets
        ./amber exec --amber-yaml amber-staging.yaml -- sh -c 'echo $API_KEY'
    - name: Another build step...
      run: |
        echo continue your actions as normal
        echo if you need access to secrets, then be sure to put AMBER_SECRET in the env
        echo and use amber exec when needed
        echo e.g. ./amber exec --amber-yaml amber-staging.yaml -- sh -c 'node test $API_KEY' 
        echo e.g. ./amber exec --amber-yaml amber-staging.yaml -- sh -c 'python -m pytest $API_KEY' 
        echo or export all as needed via amber print
